In [1]:
# Import
from __future__ import absolute_import, division, print_function

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)
tf.enable_eager_execution()

1.13.1


In [2]:
# Load Data 
filename = 'C:\\Users\\deniz\\Desktop\\Thesis of ML for AutoPas\\Data\\Results\\example2.txt'
arr = np.genfromtxt(filename, delimiter=',')

In [3]:
# Slicing the data and checking out the shape
parameter_count = 9
print(arr[:,0:parameter_count].shape)
print(arr[:,0:parameter_count])
print(arr[:,parameter_count:].shape)
print(arr[:,parameter_count:])
print(np.argmin(arr[:,parameter_count:], 1).shape)
print(np.column_stack((arr[:,0:parameter_count], np.argmin(arr[:,parameter_count:], 1))))
print(np.column_stack((arr[:,0:parameter_count], np.argmin(arr[:,parameter_count:], 1))).shape)
print(np.column_stack((arr[:,0:parameter_count], np.argmin(arr[:,parameter_count:], 1))))
nptotal = np.column_stack((arr[:,0:parameter_count], np.argmin(arr[:,parameter_count:], 1)))
npfeatures = arr[:,0:parameter_count]
nplabels = np.argmin(arr[:,parameter_count:], 1)

(700, 9)
[[5.0e+00 2.0e-01 1.0e+00 ... 6.0e+00 2.0e+00 1.0e+03]
 [5.0e+00 2.0e-01 1.5e+00 ... 6.0e+00 2.0e+00 1.0e+03]
 [5.0e+00 2.0e-01 2.0e+00 ... 6.0e+00 2.0e+00 1.0e+03]
 ...
 [5.0e+00 2.0e-01 4.5e+00 ... 7.5e+01 2.0e+00 1.0e+03]
 [5.0e+00 2.0e-01 5.0e+00 ... 7.5e+01 2.0e+00 1.0e+03]
 [5.0e+00 2.0e-01 5.5e+00 ... 7.5e+01 2.0e+00 1.0e+03]]
(700, 27)
[[  148246.   352313.   346917. ...   532576.  3450878.   527973.]
 [  162172.   498808. 26964589. ...   941041.  3793659.   595741.]
 [  307314.   959034.   716776. ...  1931228.  4267302.   910469.]
 ...
 [ 5351442.  9166906. 14905408. ... 13160724.  7483338.  6406035.]
 [ 2493910.  7916634.  6071180. ... 13402674.  7752953.  5692631.]
 [ 2352048.  8220402.  6134818. ... 18819502.  5214517.  4831940.]]
(700,)
[[5.0e+00 2.0e-01 1.0e+00 ... 2.0e+00 1.0e+03 4.0e+00]
 [5.0e+00 2.0e-01 1.5e+00 ... 2.0e+00 1.0e+03 0.0e+00]
 [5.0e+00 2.0e-01 2.0e+00 ... 2.0e+00 1.0e+03 2.2e+01]
 ...
 [5.0e+00 2.0e-01 4.5e+00 ... 2.0e+00 1.0e+03 7.0e+00]
 [5.0

In [4]:
# Eliminate Generator Type and stack the columns
parameter_count = 9
data = np.column_stack((arr[:,0:4], arr[:,5:parameter_count], np.argmin(arr[:,parameter_count:], 1)))

# Eliminate redundant data
data = data[:,[2, 4, 5, 8]]
#print(data)

# Normalize the data
def normalize01(array):
    divisor = np.max(array)
    for i in range(array.size):
        array[i] = array[i] / divisor

# Shuffle data and take 20% as test data
#np.random.shuffle(data)
test_size = (np.ceil(data.shape[0] / 5)).astype(int)
#print(test_size)
parameter_count = 3 # we have to account for eliminating the generator type
train_params = data[test_size:,0:parameter_count]
train_labels = data[test_size:,parameter_count:].astype(int)
test_params = data[:test_size,0:parameter_count]
test_labels = data[:test_size,parameter_count:].astype(int)

print(train_params)
np.apply_along_axis(normalize01, 0, train_params)
np.apply_along_axis(normalize01, 0, test_params)
print(train_params)

[[  1.   40.   20. ]
 [  1.5  40.   20. ]
 [  2.   40.   20. ]
 ...
 [  4.5 150.   75. ]
 [  5.  150.   75. ]
 [  5.5 150.   75. ]]
[[0.18181818 0.26666667 0.26666667]
 [0.27272727 0.26666667 0.26666667]
 [0.36363636 0.26666667 0.26666667]
 ...
 [0.81818182 1.         1.        ]
 [0.90909091 1.         1.        ]
 [1.         1.         1.        ]]


In [5]:
print(train_params[0])
print(test_labels.shape)

[0.18181818 0.26666667 0.26666667]
(140, 1)


In [12]:
# Model
model = keras.Sequential([
    keras.layers.Dense(9, activation=tf.nn.relu),
    keras.layers.Dense(27, activation=tf.nn.softmax)
])

opt = keras.optimizers.Adam(lr=0.01)

model.compile(optimizer=opt, 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print(parameter_count)

3


In [13]:
# Fun
model.fit(train_params, train_labels , epochs=50)

Epoch 1/50
560/560 [==============================] - 0s 762us/sample - loss: 2.8908 - acc: 0.2714
Epoch 2/50
560/560 [==============================] - 0s 68us/sample - loss: 1.7553 - acc: 0.4643
Epoch 3/50
560/560 [==============================] - 0s 66us/sample - loss: 1.4189 - acc: 0.4643
Epoch 4/50
560/560 [==============================] - 0s 75us/sample - loss: 1.3453 - acc: 0.4643
Epoch 5/50
560/560 [==============================] - 0s 68us/sample - loss: 1.2840 - acc: 0.4643
Epoch 6/50
560/560 [==============================] - 0s 75us/sample - loss: 1.2289 - acc: 0.4911
Epoch 7/50
560/560 [==============================] - 0s 64us/sample - loss: 1.1838 - acc: 0.4929
Epoch 8/50
560/560 [==============================] - 0s 77us/sample - loss: 1.1288 - acc: 0.5125
Epoch 9/50
560/560 [==============================] - 0s 80us/sample - loss: 1.0712 - acc: 0.5732
Epoch 10/50
560/560 [==============================] - 0s 66us/sample - loss: 1.0256 - acc: 0.6393
Epoch 11/50
560/56

In [14]:
predictions = model.predict(test_params)
test_loss, test_acc = model.evaluate(test_params, test_labels)
print('Test accuracy:', test_acc)

140/140 [==============================] - 0s 935us/sample - loss: 2.7301 - acc: 0.3286
Test accuracy: 0.32857144


In [15]:
# Print prediction, result, and how certain the result is
for i in range(140):
    print(np.argmax(predictions[i]), test_labels[i], np.max(predictions[i]))

4 [4] 0.9753144
4 [0] 0.96866375
4 [22] 0.8108529
7 [22] 0.2959526
0 [22] 0.35184512
22 [22] 0.461868
22 [0] 0.57936025
22 [22] 0.67924255
22 [22] 0.7587233
22 [22] 0.8192646
4 [4] 0.9741243
4 [0] 0.972787
4 [22] 0.81800306
7 [22] 0.39334318
7 [22] 0.38452744
22 [22] 0.41645342
22 [7] 0.5475317
22 [0] 0.65990275
22 [22] 0.7476868
22 [22] 0.81260896
4 [4] 0.9697299
4 [0] 0.97409374
4 [22] 0.8130015
7 [22] 0.48898458
7 [7] 0.5239335
7 [22] 0.38227797
22 [22] 0.49378
22 [11] 0.62313336
22 [7] 0.7249325
22 [22] 0.7985994
4 [4] 0.9607576
4 [0] 0.9694372
4 [0] 0.7984202
7 [22] 0.5750294
7 [22] 0.6562254
7 [0] 0.5236859
22 [22] 0.4178165
22 [22] 0.56417567
22 [11] 0.6856147
22 [11] 0.7739005
4 [4] 0.9445453
4 [0] 0.96256304
4 [22] 0.7761712
7 [22] 0.64809257
7 [22] 0.7645198
7 [22] 0.659782
7 [0] 0.49682972
22 [22] 0.48200014
22 [22] 0.6248973
22 [7] 0.7341013
4 [4] 0.9167493
4 [4] 0.952932
4 [0] 0.7476308
7 [22] 0.7082945
7 [0] 0.8434986
7 [22] 0.7722977
7 [7] 0.633301
7 [22] 0.4588055
22 [2