In [1]:
# Import
from __future__ import absolute_import, division, print_function

# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)
tf.enable_eager_execution()

1.13.1


In [2]:
# Load Data 
filename = 'C:\\Users\\deniz\\Desktop\\Thesis of ML for AutoPas\\Data\\Batch2\\exampleW.txt'
arr = np.genfromtxt(filename, delimiter=',')

In [3]:
# Slicing the data and checking out the shape
print(arr[:,0:7].shape)
print(arr[:,0:7])
print(arr[:,7:].shape)
print(arr[:,7:])
print(np.argmin(arr[:,7:], 1).shape)
print(np.column_stack((arr[:,0:7], np.argmin(arr[:,7:], 1))))
print(np.column_stack((arr[:,0:7], np.argmin(arr[:,7:], 1))).shape)
print(np.column_stack((arr[:,0:7], np.argmin(arr[:,7:], 1))))
nptotal = np.column_stack((arr[:,0:7], np.argmin(arr[:,7:], 1)))
npfeatures = arr[:,0:7]
nplabels = np.argmin(arr[:,7:], 1)

(165, 7)
[[5.0000e+00 2.0000e-01 1.0000e+00 ... 4.0000e-01 4.0000e+00 6.4000e+01]
 [5.0000e+00 2.0000e-01 1.0000e+00 ... 4.0000e-01 8.0000e+00 5.1200e+02]
 [5.0000e+00 2.0000e-01 1.0000e+00 ... 4.0000e-01 1.2000e+01 1.7280e+03]
 ...
 [5.0000e+00 2.0000e-01 4.0000e+00 ... 4.0000e-01 1.6000e+01 4.0960e+03]
 [5.0000e+00 2.0000e-01 4.0000e+00 ... 4.0000e-01 2.0000e+01 8.0000e+03]
 [5.0000e+00 2.0000e-01 4.0000e+00 ... 4.0000e-01 2.4000e+01 1.3824e+04]]
(165, 29)
[[6.79090000e+04 5.93120000e+04 5.52720000e+04 ... 5.07308000e+05
  7.05730000e+04 3.80286000e+05]
 [1.36553000e+05 1.29404000e+05 8.70470000e+04 ... 8.28705000e+05
  3.60483000e+06 4.45874000e+05]
 [2.68971000e+05 2.73783000e+05 3.08114000e+05 ... 2.00920900e+06
  4.36936900e+06 1.24391300e+06]
 ...
 [6.27022500e+06 6.67257200e+06 6.06794950e+07 ... 2.55474574e+08
  6.33594420e+07 2.44959710e+07]
 [1.41749490e+07 1.49277890e+07 2.07702428e+08 ... 4.01262388e+08
  1.77846253e+08 1.42188411e+08]
 [2.18101380e+07 2.31634430e+07 5.187

In [4]:
# Model
model = keras.Sequential([
    keras.layers.Dense(7, activation=tf.nn.relu),
    keras.layers.Dense(29, activation=tf.nn.softmax)
])

model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [5]:
# Fun
model.fit(npfeatures, nplabels, epochs=5)

Instructions for updating:
Colocations handled automatically by placer.
Epoch 1/5
165/165 [==============================] - 0s 2ms/sample - loss: 12.4244 - acc: 0.2242
Epoch 2/5
165/165 [==============================] - 0s 91us/sample - loss: 12.4232 - acc: 0.2242
Epoch 3/5
165/165 [==============================] - 0s 103us/sample - loss: 12.4189 - acc: 0.2242
Epoch 4/5
165/165 [==============================] - 0s 103us/sample - loss: 12.4166 - acc: 0.2242
Epoch 5/5
165/165 [==============================] - 0s 103us/sample - loss: 12.4139 - acc: 0.2242
